# Generated by Django 3.2.16 on 2022-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain_SPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
                ('time', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
    ]
