# Generated by Django 4.1.4 on 2022-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_auto_20221212_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Уход за телом)',
                'verbose_name_plural': 'Mountain SPA (Уход за телом)',
            },
        ),
        migrations.CreateModel(
            name='Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo_rituals/', verbose_name='фото массажа')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате x/x/x')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате x/x/x')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (вид массажа)',
                'verbose_name_plural': 'Mountain SPA (SPA-ритуалы)',
            },
        ),
        migrations.DeleteModel(
            name='Mountain_SPA',
        ),
    ]
