# Generated by Django 4.1.4 on 2022-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_save_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_menu',
            name='path',
            field=models.FileField(help_text='Это может быть только zip-файл', upload_to='static/files/', verbose_name='Закрепите файл меню'),
        ),
    ]
