# Generated by Django 3.2.16 on 2022-12-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_alter_save_menu_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sea_spa_BC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_care/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
                ('popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Уход за телом)',
                'verbose_name_plural': 'Mountain SPA (Уход за телом)',
            },
        ),
        migrations.CreateModel(
            name='Sea_SPA_RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_care/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
                ('popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Уход за телом)',
                'verbose_name_plural': 'Mountain SPA (Уход за телом)',
            },
        ),
        migrations.AddField(
            model_name='body_care',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rituals',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
