# Generated by Django 3.2.16 on 2022-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_auto_20221215_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_care',
            options={'verbose_name': 'SPA-ритуалы (Уход за телом)', 'verbose_name_plural': 'Mountain-SPA (Уход за телом)'},
        ),
        migrations.AlterModelOptions(
            name='rituals',
            options={'verbose_name': 'SPA-ритуалы (вид массажа)', 'verbose_name_plural': 'Mountain-SPA (Виды массажа)'},
        ),
        migrations.AlterModelOptions(
            name='sea_spa_bc',
            options={'verbose_name': 'SPA-ритуалы (Уход за телом)', 'verbose_name_plural': 'SEA-SPA (Уход за телом)'},
        ),
        migrations.AlterModelOptions(
            name='sea_spa_rt',
            options={'verbose_name': 'SPA-ритуалы (Вид массажа)', 'verbose_name_plural': 'SEA-SPA (Виды массажа)'},
        ),
        migrations.AddField(
            model_name='save_menu',
            name='work',
            field=models.BooleanField(default=False, verbose_name='Поставте галочку для того, что бы меню стало активным(возможен только один вариант!)'),
        ),
        migrations.AlterField(
            model_name='body_care',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные Процедуры)'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные массажи)'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='path',
            field=models.FileField(help_text='Это может быть только zip-файл', upload_to='static/files/', verbose_name='Выберите один файл, который будет педставлять ваше Меню'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные Процедуры)'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные массажи)'),
        ),
    ]
