# Generated by Django 3.2.16 on 2022-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_auto_20221215_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_menu',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
