# Generated by Django 4.1.4 on 2022-12-16 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_save_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 18, 52, 30, 281460), verbose_name='Время изменения'),
        ),
    ]
