# Generated by Django 3.2.16 on 2022-12-16 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0011_auto_20221216_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plase',
            options={'verbose_name': 'Расположения салона', 'verbose_name_plural': 'Расположение салонов'},
        ),
        migrations.AddField(
            model_name='plase',
            name='photo',
            field=models.ImageField(default=None, upload_to='static/photo/photo_salons/', verbose_name='Фото салона'),
        ),
        migrations.AlterField(
            model_name='body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 131991), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 131991), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='MY_CHOICES',
            field=models.CharField(blank=True, choices=[('KP', 'Красная Поляна'), ('PX', 'Роза Хутор'), ('GZ', 'Горно-туристический центр ПАО «Газпром»')], max_length=2, null=True, verbose_name='Расположение (выберите один из 3х варинтов)'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='adress',
            field=models.CharField(max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя SPA-салона'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер мобильного телефона'),
        ),
        migrations.AlterField(
            model_name='plase',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 131991), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 131991), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 21, 26, 43, 132988), verbose_name='Время изменения'),
        ),
    ]
