# Generated by Django 3.2.16 on 2022-12-22 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0013_auto_20221222_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town_spa_BC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_care/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
                ('time_create', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания')),
                ('time_update', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Уход за телом)',
                'verbose_name_plural': 'Town-SPA (Уход за телом)',
            },
        ),
        migrations.CreateModel(
            name='Town_SPA_RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_care/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
                ('time_create', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания')),
                ('time_update', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Вид массажа)',
                'verbose_name_plural': 'Town-SPA (Виды массажа)',
            },
        ),
        migrations.DeleteModel(
            name='Mountain_spa_BC',
        ),
        migrations.DeleteModel(
            name='Mountain_SPA_RT',
        ),
        migrations.AlterField(
            model_name='body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 34, 47, 606823), verbose_name='Время изменения'),
        ),
    ]
