# Generated by Django 3.2.16 on 2022-12-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0014_auto_20221222_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain_Body_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_care/', verbose_name='уходовое фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате "X/X/X"')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате "X/X/X"')),
                ('popular', models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные Процедуры)')),
                ('time_create', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания')),
                ('time_update', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (Уход за телом)',
                'verbose_name_plural': 'Mountain-SPA (Уход за телом)',
            },
        ),
        migrations.CreateModel(
            name='Mountain_Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/photo/photo_rituals/', verbose_name='фото массажа')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=250, verbose_name='описание')),
                ('time', models.CharField(blank=True, max_length=50, null=True, verbose_name='время в формате x/x/x')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='цена в формате x/x/x')),
                ('popular', models.BooleanField(default=False, verbose_name='Добавить на главную страницу сайта (популярные массажи)')),
                ('time_create', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания')),
                ('time_update', models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'SPA-ритуалы (вид массажа)',
                'verbose_name_plural': 'Mountain-SPA (Виды массажа)',
            },
        ),
        migrations.DeleteModel(
            name='Body_care',
        ),
        migrations.DeleteModel(
            name='Rituals',
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 21, 59, 59, 16484), verbose_name='Время изменения'),
        ),
    ]
