# Generated by Django 4.1.4 on 2022-12-23 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0015_auto_20221222_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sea_spa_bc',
            name='popular',
        ),
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 777635), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 777635), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Добавить в раздел "новые процедуры"'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 775645), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 7, 43, 776639), verbose_name='Время изменения'),
        ),
    ]
