# Generated by Django 4.1.4 on 2022-12-23 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0017_sea_spa_bc_view_sea_spa_rt_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 150126), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 150126), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 150126), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 150126), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 152121), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 152121), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='photo',
            field=models.ImageField(upload_to='static/photo/photo_rituals/', verbose_name='уходовое фото'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='photo',
            field=models.ImageField(upload_to='static/photo/photo_rituals/', verbose_name='уходовое фото'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 17, 29, 48, 151124), verbose_name='Время изменения'),
        ),
    ]
