# Generated by Django 4.1.4 on 2022-12-23 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0018_alter_mountain_body_care_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sea_spa_rt',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Добавить в раздел "Новые процедуры" '),
        ),
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_body_care',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='mountain_rituals',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='save_menu',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='sea_spa_bc',
            name='view',
            field=models.BooleanField(default=True, verbose_name='Отображать в общем меню'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sea_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 887090), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_bc',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='town_spa_rt',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 18, 8, 34, 888088), verbose_name='Время изменения'),
        ),
    ]
